import {
  GITHUB_API_BASE_URL,
  GITHUB_API_VERSION,
  GithubCredentialMode,
  HttpMethod,
} from "../core/constants";
import { bytesToBase64Url, encodeBase64UrlJson } from "../core/crypto";
import { DomainStatus, ErrorSource, ToolError, serverConfigError } from "../core/errors";
import type { Env } from "../core/types";
import { parseJson } from "./github-api";

const GITHUB_APP_JWT_TTL_SECONDS = 9 * 60;
const GITHUB_APP_TOKEN_REFRESH_MARGIN_MS = 5 * 60 * 1000;
const githubAppTokenCache = new Map<string, { token: string; expiresAt: number }>();

export function githubCredentialMode(env: Env) {
  const values = [env.GITHUB_APP_ID, env.GITHUB_APP_INSTALLATION_ID, env.GITHUB_APP_PRIVATE_KEY]
    .map((value) => value?.trim())
    .filter(Boolean);
  if (values.length > 0 && values.length < 3) {
    throw serverConfigError(
      "GitHub App configuration is incomplete.",
      "Configure GITHUB_APP_ID, GITHUB_APP_INSTALLATION_ID, and GITHUB_APP_PRIVATE_KEY together.",
      DomainStatus.GithubAppConfigInvalid,
    );
  }
  if (values.length === 3) {
    return GithubCredentialMode.App;
  }
  return GithubCredentialMode.None;
}

export function isGithubAppConfigured(env: Env) {
  return githubCredentialMode(env) === GithubCredentialMode.App;
}

export async function resolveGithubAccessToken(env: Env) {
  const mode = githubCredentialMode(env);
  if (mode === GithubCredentialMode.App) {
    return githubAppInstallationToken(env);
  }
  throw new ToolError({
    source: ErrorSource.GithubApi,
    domainStatus: DomainStatus.GithubNotConnected,
    message: "GitHub authentication is not configured.",
  });
}

export function clearGithubAppTokenCache() {
  githubAppTokenCache.clear();
}

async function githubAppInstallationToken(env: Env) {
  const appId = env.GITHUB_APP_ID!.trim();
  const installationId = env.GITHUB_APP_INSTALLATION_ID!.trim();
  if (!/^\d+$/.test(appId) || !/^\d+$/.test(installationId)) {
    throw serverConfigError(
      "GitHub App IDs must be decimal integers.",
      "Copy the App ID and installation ID from GitHub without additional text.",
      DomainStatus.GithubAppConfigInvalid,
    );
  }

  const cacheKey = `${appId}:${installationId}`;
  const cached = githubAppTokenCache.get(cacheKey);
  if (cached && cached.expiresAt > Date.now() + GITHUB_APP_TOKEN_REFRESH_MARGIN_MS) {
    return cached.token;
  }

  const jwt = await createGithubAppJwt(appId, env.GITHUB_APP_PRIVATE_KEY!);
  const response = await fetch(`${GITHUB_API_BASE_URL}/app/installations/${installationId}/access_tokens`, {
    method: HttpMethod.Post,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${jwt}`,
      "Content-Type": "application/json",
      "User-Agent": "esa-mcp-worker",
      "X-GitHub-Api-Version": GITHUB_API_VERSION,
    },
  });
  const text = await response.text();
  const body = text ? parseJson(text) : {};
  if (!response.ok) {
    throw new ToolError({
      source: ErrorSource.GithubApi,
      domainStatus: DomainStatus.GithubAppTokenFailed,
      message: `GitHub App installation token request failed: ${response.status} ${response.statusText}`,
      status: response.status,
      details: { response: body },
    });
  }

  const value = body as { token?: string; expires_at?: string };
  const expiresAt = Date.parse(value.expires_at ?? "");
  if (!value.token || !Number.isFinite(expiresAt)) {
    throw new ToolError({
      source: ErrorSource.GithubApi,
      domainStatus: DomainStatus.GithubAppTokenFailed,
      message: "GitHub App installation token response is invalid.",
    });
  }
  githubAppTokenCache.set(cacheKey, { token: value.token, expiresAt });
  return value.token;
}

export async function createGithubAppJwt(appId: string, privateKeyPem: string) {
  const now = Math.floor(Date.now() / 1000);
  const header = encodeBase64UrlJson({ alg: "RS256", typ: "JWT" });
  const payload = encodeBase64UrlJson({
    iat: now - 60,
    exp: now + GITHUB_APP_JWT_TTL_SECONDS,
    iss: appId,
  });
  const signingInput = `${header}.${payload}`;
  let key: CryptoKey;
  try {
    key = await crypto.subtle.importKey(
      "pkcs8",
      githubPrivateKeyDer(privateKeyPem),
      { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
      false,
      ["sign"],
    );
  } catch {
    throw serverConfigError(
      "GITHUB_APP_PRIVATE_KEY is not a valid GitHub App RSA private key.",
      "Paste the complete PEM file generated by GitHub into a Cloudflare encrypted secret.",
      DomainStatus.GithubAppConfigInvalid,
    );
  }
  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    key,
    new TextEncoder().encode(signingInput),
  );
  return `${signingInput}.${bytesToBase64Url(new Uint8Array(signature))}`;
}

function githubPrivateKeyDer(pem: string) {
  const normalized = pem.trim().replace(/\\n/g, "\n");
  const pkcs8 = decodePem(normalized, "PRIVATE KEY");
  if (pkcs8) {
    return pkcs8;
  }
  const pkcs1 = decodePem(normalized, "RSA PRIVATE KEY");
  if (!pkcs1) {
    throw new Error("Unsupported private key PEM format.");
  }
  const rsaAlgorithmIdentifier = new Uint8Array([
    0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00,
  ]);
  return derElement(0x30, concatBytes(
    new Uint8Array([0x02, 0x01, 0x00]),
    rsaAlgorithmIdentifier,
    derElement(0x04, pkcs1),
  ));
}

function decodePem(pem: string, label: string) {
  const match = new RegExp(`-----BEGIN ${label}-----([\\s\\S]+?)-----END ${label}-----`).exec(pem);
  if (!match) {
    return undefined;
  }
  const binary = atob(match[1]!.replace(/\s+/g, ""));
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

function derElement(tag: number, content: Uint8Array) {
  return concatBytes(new Uint8Array([tag]), derLength(content.length), content);
}

function derLength(length: number) {
  if (length < 0x80) {
    return new Uint8Array([length]);
  }
  const bytes: number[] = [];
  for (let value = length; value > 0; value >>>= 8) {
    bytes.unshift(value & 0xff);
  }
  return new Uint8Array([0x80 | bytes.length, ...bytes]);
}

function concatBytes(...parts: Uint8Array[]) {
  const result = new Uint8Array(parts.reduce((total, part) => total + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}
